spring:
#  devtools:
#    livereload:
#      enabled: true
  config:
    import:
      - optional:env.yml
  output:
    ansi:
      enabled: always
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true